language: node_js
node_js:
- '8'
- '7'
after_script:
-scp -o StrictHostKeyChecking=no ./src -r root@47.95.239.252:/home/www/dql
before_install:
- openssl aes-256-cbc -K $encrypted_08aee97bc2e9_key -iv $encrypted_08aee97bc2e9_iv
 -in ./.travis/du_key.enc -out ./.travis/du_key -d
 - mv du_key ~/.ssh/ -f
 - chmod 600 ~/.ssh/du_key
 - eval$(ssh-agent)
 - ssh-add ~/.ssh/du_key
 - cp .travis/ssh_config ~/.ssh/config




